# Generated by Django 3.0.7 on 2020-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200907_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('yoghurt', 'yoghurt'), ('shawarma', 'shawarma'), ('cake', 'cake'), ('pop-corn', 'pop-corn'), ('yoghurt', 'yoghurt'), ('smothie', 'smothie'), ('grill', 'grill'), ('bread', 'bread')], max_length=20),
        ),
    ]
