# Generated by Django 3.0.7 on 2020-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200914_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_image',
            field=models.CharField(default='images/users/ygig.jpg', max_length=200, null=True),
        ),
    ]
