# Generated by Django 3.0.7 on 2020-09-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('yoghurt', 'yoghurt'), ('shawarma', 'shawarma'), ('cake', 'cake'), ('pop-corn', 'pop-corn'), ('smothie', 'smothie'), ('grill', 'grill'), ('bread', 'bread'), ('toppings', 'toppings')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_image',
            field=models.CharField(default='/images/images/users/ygig.png', max_length=200, null=True),
        ),
    ]
