# Generated by Django 3.0.7 on 2020-09-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200915_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('yoghurt', 'yoghurt'), ('shawarma', 'shawarma'), ('cake', 'cake'), ('pop-corn', 'pop-corn'), ('smothie', 'smothie'), ('grill', 'grill'), ('bread', 'bread'), ('toppings', 'toppings'), ('drink', 'drink')], max_length=20),
        ),
    ]
