# Generated by Django 3.0.7 on 2020-09-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_auto_20200914_0157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chef',
        ),
    ]
